export interface McpServerRecord {
  id: string;
  name: string;
  install_command: string;
  required_env_vars: any;
}

export interface AiSkillRecord {
  id: string;
  name: string;
  skill_content: string;
}

export class ConfigGenerator {
  /**
   * Generates target client configuration JSON snapshot
   */
  public static generate(
    clientType: string,
    servers: McpServerRecord[],
    skills: AiSkillRecord[]
  ): Record<string, any> {
    const mcpServersMap: Record<string, any> = {};

    for (const server of servers) {
      // Parse command parts (e.g., "npx -y @modelcontextprotocol/server-postgres postgresql://...")
      const parts = server.install_command.split(' ');
      const command = parts[0] || 'npx';
      const args = parts.slice(1);

      // Build env template
      const env: Record<string, string> = {};
      if (Array.isArray(server.required_env_vars)) {
        for (const varName of server.required_env_vars) {
          if (typeof varName === 'string') {
            env[varName] = `YOUR_${varName}_HERE`;
          }
        }
      }

      mcpServersMap[server.name] = {
        command,
        args,
        env,
      };
    }

    const skillsCatalog = skills.map((skill) => ({
      name: skill.name,
      contentSummary: skill.skill_content.slice(0, 150) + (skill.skill_content.length > 150 ? '...' : ''),
      content: skill.skill_content,
    }));

    switch (clientType.toLowerCase()) {
      case 'claude_desktop':
        return {
          mcpServers: mcpServersMap,
          _comment: 'Generated by ContextForge for Claude Desktop',
          skills: skillsCatalog,
        };

      case 'cursor':
        return {
          mcpServers: mcpServersMap,
          skills: skillsCatalog,
        };

      case 'cline':
        return {
          mcpServers: mcpServersMap,
        };

      case 'antigravity':
        return {
          $schema: 'https://antigravity.dev/schemas/mcp.json',
          mcpServers: mcpServersMap,
          skills: skillsCatalog,
        };

      default:
        return {
          clientType,
          mcpServers: mcpServersMap,
          skills: skillsCatalog,
        };
    }
  }
}
